version: '3.8'

# Development-only docker-compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    ports:
      - "0.0.0.0:5432:5432"  # Expose PostgreSQL for local development
    environment:
      POSTGRES_PASSWORD: crmpassword  # Simple password for dev
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./backups:/backups  # Mount backups directory

  # Development version - mount source code for hot reload
  crm-server:
    build:
      context: .
      dockerfile: Dockerfile.crm.dev
    volumes:
      - .:/app
      - /app/vendor  # Exclude vendor directory
    environment:
      CGO_ENABLED: 1
      GOOS: linux
      DEVELOPMENT: "true"
    command: ["go", "run", "./cmd/crm"]

  # Add Adminer as a lightweight alternative to pgAdmin for dev
  adminer:
    image: adminer:latest
    container_name: crm-adminer
    ports:
      - "0.0.0.0:8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - postgres
    networks:
      - crm-network